name: Generate folders

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Print current directory
      run: |
        pwd
        ls -la
        
    - name: List directory before running script
      run: ls -la

    - name: Run script to create directories
      run: |
        python create_folders.py

    - name: List directory after running script
      run: ls -la

    - name: Configure Git
      run: |
        git config --global user.name 'usman6036'
        git config --global user.email 'usmansaleem2799@gmail.com'

    - name: Commit and Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git status
        git add .
        git commit -m "Create successful and unsuccessful directories"
        git push
