name: Generate folders

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Create directories
      run: |
        mkdir -p test_directory/subdirectory
        echo "Hello, World!" > test_directory/hello.txt

    - name: List files before commit
      run: ls -la

    - name: Configure Git
      run: |
        git config --global user.name 'usman6036'
        git config --global user.email 'usmansaleem2799@gmail.com'

    - name: Commit changes
      run: |
        git add test_directory
        git commit -m "Add test_directory with files"
      
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin master
